name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install system deps
        run: |
          sudo apt update
          sudo apt install -y \
            python3-pip \
            python3-setuptools \
            git \
            zip \
            unzip \
            openjdk-17-jdk \
            autoconf \
            libtool \
            pkg-config \
            zlib1g-dev \
            libncurses5-dev \
            libncursesw5-dev \
            libtinfo5 \
            cmake \
            libffi-dev \
            libssl-dev

      - name: Install Python deps
        run: |
          pip3 install --upgrade pip
          pip3 install buildozer cython

      - name: Build APK
        run: |
          buildozer init
          buildozer android debug
